### ISSUE TITLE
[Bug] handleSocialClick redirect bug

### ISSUE THREAD

**Issue by eavlongs** [s1lvax/route#104]
In the file `src/lib/utils/handleSocialClick.ts`, when `socialData.redirect` is set to true, the function should redirect the user to the specified URL in a new tab. However, since we currently do not validate user-provided social URLs, if a user inputs a URL like `example.com` without including `https://`, the function will redirect the user to a new tab with the route: https://route2.dev/example.com.

**Comment by s1lvax** [comment]
This is indeed a problem. I wonder how we can solve this seeing that some socials required an URL and others a username

**Comment by eavlongs** [comment]
Can you provide more information on why we are using URLs and usernames for social media forms? Why not just use URL only?

**Comment by eavlongs** [comment]
After conducting some research, I found that Discord does not support links to user profiles. Additionally, I noticed you have Spotify integration, which requires a user ID.

**Comment by s1lvax** [comment]
Yep, that's right
