### ISSUE TITLE
[Feature] Ability to change the order of Links and entries in Tech Stack

### ISSUE THREAD

**Issue by glitchingcore** [s1lvax/route#15]

**Comment by Butugey12** [comment]
Hello, I can do this one.

**Comment by Butugey12** [comment]
Just to make sure, You want a DnD Reordering functionality for Link and Skills Entries?
Something like this:
https://svelte.dev/repl/aca4db78b927481db958df190b5d7d6e?version=3.38.2

**Comment by glitchingcore** [comment]
Hey, to make sure efforts don't go to waste I would like to say that I am actually about to finish making a PR implementing this feature with the same library you've proposed.
I am not sure how clean my solution is, so feel free to correct any issues you will find in my code!

**Comment by Butugey12** [comment]
@glitchingcore Thanks for the heads up
