### ISSUE TITLE
[Bug] Change the "Tech Stack" title to "Skills"

### ISSUE THREAD

**Issue by s1lvax** [s1lvax/route#56]

**Comment by Brijeshthummar02** [comment]
@s1lvax hey there, i can do it,  show me the path to file where you wanted changes.

**Comment by amananand20** [comment]
Hi @s1lvax, have raised PR #60 to fix this issue. Let me know if you need any improvements on this.

**Comment by Brijeshthummar02** [comment]
@amananand20 you raised pr without letting assign the issue to you, that's against guidelines you should be aware about it.
@s1lvax as i was first to ask about assign this task to me, i request you @s1lvax not to consider @amananand20 pull request, i hope you understand it.
