### ISSUE TITLE
[Bug] Mastery level displayed as "undefined" if none is chosen

### ISSUE THREAD

**Issue by Discusser** [s1lvax/route#75]
You can add a skill to your profile without specifying the mastery level, and it ends up being set to undefined:

![image](https://github.com/user-attachments/assets/fb9c6b1c-6221-41f3-8a48-dd3ce7b5f603)

**Comment by tawaks** [comment]
For handling unselected mastery levels, here are common alternatives we can choose:

1. Prevent submission without a level (Required field)
2. Display a default placeholder text like "Not specified" or "Unrated"
3. Set a default value like "Novice" (level 1)

What do you think should happen?

**Comment by s1lvax** [comment]
I think the first one is the right choice. It should be mandatory; I need to check what's wrong with the form.

**Comment by tawaks** [comment]
If it's okay, I can add code to prevent submission without a level.

**Comment by s1lvax** [comment]
Of course, it's all yours :)).

**Comment by tawaks** [comment]
Thanks
