### ISSUE TITLE
[Bug] You can't click on Open to collaboration toggle

### ISSUE THREAD

**Issue by jcubic** [s1lvax/route#84]
You can only click on label and not on the toggle, which looks like a UX bug to me.

**Comment by s1lvax** [comment]
Hi there and welcome to the project :D @jcubic .

Thanks for pointing this out.
It was just an horrible design idea on my part, I will change this soon to just be a normal button.

**Comment by jcubic** [comment]
You can make Toggle like this in Pure CSS. There are a lot of examples online.

Here is mine that I did long ago:

https://codepen.io/jcubic/pen/WXLKeQ

The old code require the label to be after the input, but now with `:has()` selector, you can make the label before the input. Another way is to [change the order with flexbox](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Ordering_flex_items).

**Comment by s1lvax** [comment]
Thank you, I'll give a try :))
